controllers:
    resource: ../src/Controller/
    type: attribute

live_component:
    resource: '@LiveComponentBundle/Resources/config/routing/live_component.xml'
    # uncomment to add localization to your components
    #prefix: '/{_locale}'
